core/urls.py
from django.urls import path
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    add_wholesaler_to_cart,
    remove_from_cart,
    remove_wholesaler_from_cart,
    remove_single_item_from_cart,
    remove_single_wholesaler_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    WholesalerListView,
    WholesalerDetailView,
    PaymentViewC
)
from . import views
from django.conf.urls import url, include
app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    #path('<crown>/<crown_id<slug>/', HomeView.as_view(), name='crown'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('wholesalers/', WholesalerListView.as_view(), name='wholesalers'),
    #path('wholesalers/men.html/', WholesalerListView.as_view(), name='wholesalers/men.html'),
    path('wholesaler/<slug>/', WholesalerDetailView.as_view(), name='wholesaler'),
    path('wholesalers/men.html/', WholesalerListView.as_view(), name='men.html'),#url for displaying menu items in wholesale category i.e men,women,kids,discover
    path('wholesalers/women.html/', WholesalerListView.as_view(), name='women.html'),
    path('wholesaler/<slug>/<id>/', WholesalerDetailView.as_view(), name='wholesaler'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-wholesaler-to-cart/<slug>/<id>/', add_wholesaler_to_cart, name='add-wholesaler-to-cart'),
    path('add-wholesaler-to-cart/<slug>/', add_wholesaler_to_cart, name='add-wholesaler-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-wholesaler-from-cart/<slug>/<id>/', remove_wholesaler_from_cart, name='remove-wholesaler-from-cart'),
    path('remove-wholesaler-from-cart/<slug>/', remove_wholesaler_from_cart, name='remove-wholesaler-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('remove-single-wholesaler-from-cart/<slug>/', remove_single_wholesaler_from_cart,
         name='remove-single-wholesaler-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('paymentc/<payment_option>/', PaymentViewC.as_view(), name='paymentc'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    #path('search/', SearchView.as_view(), name='search'),
    url(r'^search/', include('haystack.urls')),
]

core/models.py
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField


CATEGORY_CHOICES = (
    ('M', 'MEN'),
    ('W', 'WOMEN'),
    ('K/B', 'KIDS/BABY'),
    ('D', 'DISCOVER')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)

SIZE_CHOICES = (
    ('sm', 'small'),
    ('m', 'medium'),
    ('l', 'large'),
    ('xl', 'extra large'),
    ('xxl', 'extra extra large')
)


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

class Crown(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'crown'
        verbose_name_plural = 'crowns'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('core:wholesalers_by_crown', kwargs={
            'slug': self.slug
        })


class Item(models.Model):
    crown = models.ForeignKey(Crown, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=3)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField(default=5)
    item_size = models.CharField(choices=SIZE_CHOICES, max_length=2)
    image = models.ImageField(upload_to='items/%Y/%m/%d')
    image_1 = models.ImageField(upload_to='items/%Y/%m/%d/', blank=True)
    image_2 = models.ImageField(upload_to='items/%Y/%m/%d/', blank=True)


    class Meta:
        ordering = ('title', )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()

class Wholesaler(models.Model):
    crown = models.ForeignKey(Crown,
        related_name = 'crown', on_delete=models.CASCADE)
    title = models.CharField(max_length=100, blank=True, db_index=True)
    price = models.FloatField()
    min_quantity = models.IntegerField(default=5)
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=3)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField(max_length=100, db_index=True, blank=True )
    description = models.TextField()
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField(default=5)
    wholesaler_size = models.CharField(choices=SIZE_CHOICES, max_length=2)
    image = models.ImageField(upload_to='items/%Y/%m/%d')
    image_1 = models.ImageField(upload_to='items/%Y/%m/%d/', blank=True)


    class Meta:
        ordering = ('title', )
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:wholesaler", kwargs={
            'slug': self.slug,
            'id': self.id
        })

    def get_add_wholesaler_to_cart_url(self):
        return reverse("core:add-wholesaler-to-cart", kwargs={
            'slug': self.slug,
            'id': self.id
        })

    def get_remove_wholesaler_from_cart_url(self):
        return reverse("core:remove-wholesaler-from-cart", kwargs={
            'slug': self.slug,
            'id': self.id
        })

class OrderWholesaler(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    wholesaler = models.ForeignKey(Wholesaler, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.wholesaler.title}"

    def get_total_wholesaler_price(self):
        return self.quantity * self.wholesaler.price

    def get_total_discount_wholesaler_price(self):
        return self.quantity * self.wholesaler.discount_price

    def get_amount_saved(self):
        return self.get_total_wholesaler_price() - self.get_total_discount_wholesaler_price()

    def get_final_price(self):
        if self.wholesaler.discount_price:
            return self.get_total_discount_wholesaler_price()
        return self.get_total_wholesaler_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem, blank=True)
    item_size = models.ForeignKey(
          'Item',  related_name='size', on_delete=models.SET_NULL, blank=True, null=True)
    wholesalers = models.ManyToManyField(OrderWholesaler, blank=True)
    wholesaler_size = models.ForeignKey(
       'Wholesaler',  related_name='size', on_delete=models.SET_NULL, blank=True, null=True)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=3, default=False)

    '''
    1. Item added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total

    def get_wholesaler_total(self):
        total = 0
        for order_wholesaler in self.wholesalers.all():
            total += order_wholesaler.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total



class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

class PaymentC(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'PaymentsC'

class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):

templates/cod.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}

  <main >
    <div class="container wow fadeIn">
      <h2 class="my-5 h2 text-center">Cash On Delivery Form</h2>
      <div class="row">
        <div class="col-md-12 mb-4">

              <form action="." method="POST" class="card-body">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="btn btn-primary" value="Submit order">
              </form>
        <div class="col-md-12 mb-4">
          {% include "order_snippet.html" %}
        </div>

       </div>

      </div>
     </div>

  </main>

{% endblock content %}

templates/home.html
{% extends "base.html" %}

{% block content %}
  <main>

  <div class="container">

    <div class="container-fluid">


      <div class="navbar-header">
        <!--Navbar-->

           <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

             <!-- Navbar brand -->
           <span class="navbar-brand">Category:</span>

          <div class="container">
             <!-- Collapse button -->

             <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
               aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>

             </button>
               <!-- Collapsible content -->

                  <div class="collapse navbar-collapse" id="basicExampleNav">

               <!-- Links -->
               <div class="btn-group-vertical">
                 <ul class="nav navbar-nav navbar margin-right">
                     <li class="nav-item active">

                      <a class="nav-link" href="/">INDIVIDUAL
                      </a>


                     </li>
                     <li class="nav-item active">

                       <a class="nav-link" href="{% url 'core:wholesalers' %}">WHOLESALE
                       </a>

                     </li>

                    </ul>
               </div>
               <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link" href="/men.html/">MEN</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/women.html/">W0MEN</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/kids.html/">KIDS/BABY</a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="/">DISCOVER
                    <span class="sr-only">(current)</span>
                  </a>
                </li>

              </ul>
               <!-- Links -->
             </div>
            </div>
             <!-- Collapsible content -->

           </nav>
           <!--/.Navbar-->
         </div>

      </div>


        <!--Section: Products v.3-->
        <section class="text-center mb-4">

          <div class="row wow fadeIn">

            {% for item in object_list %}
            <div class="col-lg-3 col-md-6 mb-4">

              <div class="card">

                <div class="view overlay">
                  {% comment %} <img src="/media/" class="card-img-top" {% endcomment %}
                  <img src="{{ item.image.url }}" class="card-img-top">
                  <a href="{{ item.get_absolute_url }}">
                    <div class="mask rgba-white-slight"></div>
                  </a>
                </div>

                <div class="card-body text-left">
                  <a href="" class="grey-text">
                    <h5>{{ item.get_category_display }}</h5>
                  </a>
                  <h5>
                    <strong>
                      <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                        <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                      </a>
                    </strong>
                  </h5>

                  <h4 class="font-weight-bold blue-text">
                    <strong>KSH
                    {% if item.discount_price %}
                    {{ item.discount_price }}
                    {% else %}
                    {{ item.price }}
                    {% endif %}
                    </strong>
                  </h4>

                </div>

              </div>

            </div>
            {% endfor %}
          </div>

        </section>
        <!--Section: Products v.3-->

        <!--Pagination-->

        {% if is_paginated %}
        <nav class="d-flex justify-content-center wow fadeIn">
          <ul class="pagination pg-blue">

            {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
              </a>
            </li>
            {% endif %}

            <li class="page-item active">
              <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
                <span class="sr-only">(current)</span>
              </a>
            </li>

            {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
              </a>
            </li>
            {% endif %}
          </ul>
        </nav>
        {% endif %}

    </div>
  </main>

{% endblock content %}

templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your cart</span>
    <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
        <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
        <small class="text-muted">{{ order_item.item.description}}</small>
        </div>
        <span class="text-muted">KSH{{ order_item.get_final_price }}</span>
    </li>
    {% endfor %}
    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success">-KSH{{ order.coupon.amount }}</span>
    </li>
    {% endif %}
    <li class="list-group-item d-flex justify-content-between">
        <span>Total (KSH)</span>
        <strong>KSH{{ order.get_total }}</strong>
    </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
            <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
            </div>
        </div>
    </form>
    {% endif %}

</div>

templates/order_summary.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div class="container">

    <div class="table-responsive text-nowrap">
    <h2>Order Summary</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Item Title</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Item Price</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in object.items.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.item.title }}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
                <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}">
                  <i class="fas fa-minus mr-2"></i></a>
                {{ order_item.quantity }}
                <a href="{% url 'core:add-to-cart' order_item.item.slug %}">
                  <i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>
            {% if order_item.item.discount_price %}
                KSH{{ order_item.get_total_discount_item_price }}
                <span class="badge badge-primary">Saving KSH{{ order_item.get_amount_saved }}</span>
            {% else %}
                KSH{{ order_item.get_total_item_price }}
            {% endif %}
            <a style='color: red;' href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                <i class="fas fa-trash float-right"></i>
            </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='5'>You did not order any item</td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endfor %}
        {% if object.coupon %}
        <tr>
            <td colspan="4"><b>Coupon</b></td>
            <td><b>-KSH{{ object.coupon.amount }}</b></td>
        </tr>
        {% endif %}
        {% if object.get_total %}
        <tr>
            <td colspan="4"><b>Item Order Total</b></td>
            <td><b>KSH{{ object.get_total }}</b></td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-warning float-right ml-2' href='/checkout/'>Proceed to checkout</a>
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endif %}
    </table>
    <table class="table">
      <thead>
      <tr>
          <th scope="col">#</th>
          <th scope="col">Wholesaler Title</th>
          <th scope="col">Price</th>
          <th scope="col">Quantity</th>
          <th scope="col">Total Wholesaler Price</th>
      </tr>
      </thead>
      <tbody>
        {% for order_wholesaler in object.wholesalers.all %}
<tr>
    <th scope="row">{{ forloop.counter }}</th>
    <td>{{ order_wholesaler.wholesaler.title }}</td>
    <td>{{ order_wholesaler.wholesaler.price }}</td>
    <td>
        <a href="{% url 'core:remove-single-wholesaler-from-cart' order_wholesaler.wholesaler.slug %}">
          <i class="fas fa-minus mr-2"></i></a>
        {{ order_wholesaler.quantity }}
        <a href="{% url 'core:add-wholesaler-to-cart' order_wholesaler.wholesaler.slug %}">
          <i class="fas fa-plus ml-2"></i></a>
    </td>
    <td>
    {% if order_wholesaler.wholesaler.discount_price %}
        KSH{{ order_wholesaler.get_total_discount_wholesaler_price }}
        <span class="badge badge-primary">Saving KSH{{ order_wholesaler.get_amount_saved }}</span>
    {% else %}
        KSH{{ order_wholesaler.get_total_wholesaler_price }}
    {% endif %}
    <a style='color: red;' href="{% url 'core:remove-wholesaler-from-cart' order_wholesaler.wholesaler.slug %}">
        <i class="fas fa-trash float-right"></i>
    </a>
    </td>
</tr>
{% empty %}
<tr>
    <td colspan='5'>You did not order wholesaler products</td>
</tr>
<tr>
    <td colspan="5">
    <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
    </td>
</tr>
{% endfor %}
{% if object.coupon %}
<tr>
    <td colspan="4"><b>Coupon</b></td>
    <td><b>-KSH{{ object.coupon.amount }}</b></td>
</tr>
{% endif %}
{% if object.get_wholesaler_total %}
<tr>
    <td colspan="4"><b> Wholesaler Order Total</b></td>
    <td><b>KSH{{ object.get_wholesaler_total }}</b></td>
</tr>
<tr>
    <td colspan="5">
    <a class='btn btn-warning float-right ml-2' href='/checkout/'>Proceed to checkout</a>
    <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
    </td>
</tr>
{% endif %}
        </tbody>
    </table>

    </div>

    </div>
  </main>

{% endblock content %}

templates/wholesalers.html
{% extends "base.html" %}

{% block content %}
  <main>

  <div class="container">

    <div class="container-fluid">


      <div class="navbar-header">
        <!--Navbar-->

           <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

             <!-- Navbar brand -->
           <span class="navbar-brand">Menu:</span>

      <div class="container">
             <!-- Collapse button -->

             <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
               aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>

             </button>
               <!-- Collapsible content -->

                  <div class="collapse navbar-collapse" id="basicExampleNav">

               <!-- Links -->
               <div class="btn-group-vertical">
                 <ul class="nav navbar-nav navbar margin-right">
                     <li class="nav-item active">

                      <a class="nav-link" href="/">INDIVIDUAL
                      </a>


                     </li>
                     <li class="nav-item active">

                       <a class="nav-link" href="{% url 'core:wholesalers' %}">WHOLESALE
                       </a>

                     </li>
                    </ul>
               </div>
               <ul class="navbar-nav mr-auto">
                 <li class="nav-item">
                   <a class="nav-link" href="/wholesalers/men.html/">MEN</a>
                 </li>
                 <li class="nav-item">
                   <a class="nav-link" href="/wholesalers/women.html/">W0MEN</a>
                 </li>
                 <li class="nav-item">
                   <a class="nav-link" href="/wholesalers/kids.html/">KIDS/BABY</a>
                 </li>
                 <li class="nav-item active">
                   <a class="nav-link" href="/">DISCOVER
                     <span class="sr-only">(current)</span>
                   </a>
                 </li>

               </ul>
               <!-- Links -->
             </div>
            </div>
             <!-- Collapsible content -->

           </nav>
           <!--/.Navbar-->
         </div>

      </div>


        <!--Section: Products v.3-->
        <section class="text-center mb-4">

          <div class="row wow fadeIn">

            {% for  wholesaler in object_list %}
            <div class="col-lg-3 col-md-6 mb-4">

              <div class="card">

                <div class="view overlay">
                  {% comment %} <img src="/media/" class="card-img-top" {% endcomment %}
                  <img src="{{ wholesaler.image.url }}" class="card-img-top">
                  <a href="{{ wholesaler.get_absolute_url }}">
                    <div class="mask rgba-white-slight"></div>
                  </a>
                </div>

                <div class="card-body text-left">
                  <a href="" class="grey-text">
                    <h5>{{ wholesaler.get_category_display }}</h5>
                  </a>
                  <h5>
                    <strong>
                      <a href="{{ wholesaler.get_absolute_url }}" class="dark-grey-text">{{ wholesaler.title }}
                        <span class="badge badge-pill {{ wholesaler.get_label_display }}-color">NEW</span>
                      </a>
                    </strong>
                  </h5>

                  <h4 class="font-weight-bold blue-text">
                    <strong>KSH
                    {% if wholesaler.discount_price %}
                    {{ wholesaler.discount_price }}
                    {% else %}
                    {{ wholesaler.price }}
                    {% endif %}
                    </strong>
                  </h4>

                </div>

              </div>

            </div>
            {% endfor %}
          </div>

        </section>
        <!--Section: Products v.3-->

        <!--Pagination-->

        {% if is_paginated %}
        <nav class="d-flex justify-content-center wow fadeIn">
          <ul class="pagination pg-blue">

            {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
              </a>
            </li>
            {% endif %}

            <li class="page-item active">
              <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
                <span class="sr-only">(current)</span>
              </a>
            </li>

            {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
              </a>
            </li>
            {% endif %}
          </ul>
        </nav>
        {% endif %}

    </div>
  </main>

{% endblock content %}